# Generated by Django 4.2.2 on 2023-07-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='score_calculated_at',
            new_name='urgency_calculated_at',
        ),
    ]
