ALTER TABLE tasks ADD COLUMN rrule TEXT;
ALTER TABLE tasks ADD COLUMN dtstart TIMESTAMPTZ;
ALTER TABLE tasks ADD COLUMN dtend TIMESTAMPTZ;
ALTER TABLE tasks ADD COLUMN priority INTEGER DEFAULT 0 NOT NULL;
-- ALTER TABLE tasks ADD COLUMN percent_complete INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE tasks ADD COLUMN due TIMESTAMPTZ;
ALTER TABLE tasks ADD COLUMN sequence INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE tasks ADD COLUMN urgency INTEGER DEFAULT 0 NOT NULL;
