# Generated by Django 4.2.2 on 2023-06-15 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('rrule', models.CharField(blank=True, max_length=255, null=True, validators=[tasks.models.validate_rrule])),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.IntegerField(choices=[(1, 'Completed'), (2, 'Uncompleted'), (3, 'Deleted')])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'indexes': [models.Index(fields=['task'], name='tasks_taske_task_id_a9e106_idx'), models.Index(fields=['event_type'], name='tasks_taske_event_t_a4c42f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['uid'], name='tasks_task_uid_9e696f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['start', 'end'], name='tasks_task_start_f5d1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due'], name='tasks_task_due_f51446_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['active'], name='tasks_task_active_1054f8_idx'),
        ),
    ]
