# Generated by Django 4.2.2 on 2023-07-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasklist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='ordered_tasks',
            field=models.JSONField(blank=True, default=set),
        ),
    ]
