# Generated by Django 4.2.2 on 2023-07-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.FloatField(default=0.8),
        ),
    ]
