# Generated by Django 4.2.2 on 2023-07-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_priority_task_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='urgency',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'High'), (5, 'Medium'), (9, 'Low')], default=9),
        ),
        migrations.AlterField(
            model_name='task',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
